from fpdf import FPDF
import re


def generate_pdf(plan_text, transport_mode="plane"):
    pdf = FPDF()
    pdf.set_auto_page_break(auto=True, margin=15)
    pdf.add_page()
    pdf.set_margins(20, 20, 20)

    # Title
    pdf.set_font("Helvetica", "B", 18)
    pdf.set_text_color(26, 107, 138)
    pdf.cell(0, 12, "Wayfairy Travel Plan", ln=True, align="C")
    pdf.set_font("Helvetica", "", 9)
    pdf.set_text_color(107, 114, 128)
    pdf.cell(0, 6, "Generated by Wayfairy · AI Travel Planner", ln=True, align="C")
    pdf.ln(4)

    # Body
    pdf.set_text_color(26, 26, 46)
    for line in plan_text.split("\n"):
        line = line.strip()
        # Strip markdown symbols
        line = re.sub(r"^#{1,6}\s*", "", line)
        line = re.sub(r"\*\*(.*?)\*\*", r"\1", line)
        line = re.sub(r"\*(.*?)\*", r"\1", line)
        line = re.sub(r"`(.*?)`", r"\1", line)
        # Remove emojis and non-latin chars that fpdf can't render
        line = line.encode("latin-1", errors="ignore").decode("latin-1")

        if not line:
            pdf.ln(3)
            continue

        if re.match(r"^(Day \d+|#{1,3}|\*\*)", line) or line.isupper():
            pdf.set_font("Helvetica", "B", 11)
        elif line.startswith("-") or line.startswith("•"):
            pdf.set_font("Helvetica", "", 10)
            line = "  " + line
        else:
            pdf.set_font("Helvetica", "", 10)

        pdf.multi_cell(0, 6, line)

    # Footer
    pdf.ln(6)
    pdf.set_font("Helvetica", "", 8)
    pdf.set_text_color(160, 152, 144)
    pdf.cell(0, 6, "Wayfairy · AI Travel Planner · Made with love by Hassaan Raza", align="C")

    return bytes(pdf.output())