from fpdf import FPDF
import re


def clean(text: str) -> str:
    """Strip markdown and encode safely to latin-1."""
    text = re.sub(r"^#{1,6}\s*", "", text)
    text = re.sub(r"\*\*(.*?)\*\*", r"\1", text)
    text = re.sub(r"\*(.*?)\*", r"\1", text)
    text = re.sub(r"`(.*?)`", r"\1", text)
    # Replace common unicode chars that have latin-1 equivalents
    text = text.replace("\u2013", "-").replace("\u2014", "-")
    text = text.replace("\u2019", "'").replace("\u2018", "'")
    text = text.replace("\u201c", '"').replace("\u201d", '"')
    text = text.replace("\u00b7", "-").replace("\u2022", "-")
    text = text.replace("\u00b0", " deg")
    # Strip anything else that can't encode
    text = text.encode("latin-1", errors="ignore").decode("latin-1")
    return text.strip()


def is_table_line(line: str) -> bool:
    return "|" in line


def render_table(pdf, lines, col_w):
    """Render a markdown table as simple two-column rows."""
    for line in lines:
        if re.match(r"^\s*\|[-| :]+\|\s*$", line):
            continue  # skip separator row
        cells = [c.strip() for c in line.strip().strip("|").split("|")]
        cells = [clean(c) for c in cells if c.strip()]
        if not cells:
            continue
        pdf.set_text_color(26, 26, 46)
        if len(cells) == 1:
            pdf.set_x(pdf.l_margin)
            pdf.set_font("Helvetica", "B", 10)
            pdf.multi_cell(col_w, 6, cells[0])
        else:
            # Left cell = 55% width, right cell = 45%
            left_w = col_w * 0.55
            right_w = col_w * 0.45
            x = pdf.l_margin
            y = pdf.get_y()
            pdf.set_font("Helvetica", "B" if y == pdf.get_y() and cells == cells else "", 9)
            # Left cell
            pdf.set_xy(x, y)
            pdf.set_font("Helvetica", "", 9)
            pdf.cell(left_w, 6, cells[0][:50])
            # Right cell
            pdf.set_xy(x + left_w, y)
            pdf.cell(right_w, 6, cells[1][:30] if len(cells) > 1 else "")
            pdf.ln(6)


def generate_pdf(plan_text, transport_mode="plane"):
    pdf = FPDF()
    pdf.set_margins(20, 20, 20)
    pdf.set_auto_page_break(auto=True, margin=15)
    pdf.add_page()

    col_w = pdf.w - pdf.l_margin - pdf.r_margin

    # ── Title ──
    pdf.set_font("Helvetica", "B", 18)
    pdf.set_text_color(26, 107, 138)
    pdf.cell(col_w, 12, "Wayfairy Travel Plan", ln=True, align="C")
    pdf.set_font("Helvetica", "", 9)
    pdf.set_text_color(107, 114, 128)
    pdf.cell(col_w, 6, "Generated by Wayfairy - AI Travel Planner", ln=True, align="C")
    pdf.ln(4)

    # ── Body ──
    lines = plan_text.split("\n")
    i = 0
    while i < len(lines):
        raw = lines[i]

        # Collect table blocks
        if is_table_line(raw):
            table_block = []
            while i < len(lines) and is_table_line(lines[i]):
                table_block.append(lines[i])
                i += 1
            render_table(pdf, table_block, col_w)
            continue

        line = clean(raw)

        if not line:
            pdf.ln(3)
            i += 1
            continue

        # Always reset x to left margin before rendering
        pdf.set_x(pdf.l_margin)

        # Detect heading: original line started with #
        if re.match(r"^#{1,3}\s", raw.strip()):
            pdf.set_font("Helvetica", "B", 13)
            pdf.set_text_color(26, 107, 138)
            pdf.multi_cell(col_w, 8, line)
            pdf.set_text_color(26, 26, 46)

        # Day heading
        elif re.match(r"^Day \d+", line):
            pdf.ln(2)
            pdf.set_x(pdf.l_margin)
            pdf.set_font("Helvetica", "B", 11)
            pdf.set_text_color(26, 107, 138)
            pdf.multi_cell(col_w, 7, line)
            pdf.set_text_color(26, 26, 46)

        # Sub-headings like "Morning", "Afternoon", "Evening", "Lunch"
        elif re.match(r"^(Morning|Afternoon|Evening|Lunch|Dinner|Night)\b", line):
            pdf.set_font("Helvetica", "B", 10)
            pdf.set_text_color(60, 60, 80)
            pdf.multi_cell(col_w, 6, line)
            pdf.set_text_color(26, 26, 46)

        # Budget lines
        elif "Budget Estimate" in line or "TOTAL" in line.upper():
            pdf.set_font("Helvetica", "B", 10)
            pdf.set_text_color(201, 168, 76)
            pdf.multi_cell(col_w, 6, line)
            pdf.set_text_color(26, 26, 46)

        # Bullet / list items
        elif line.startswith("-") or line.startswith("*") or line.startswith("•"):
            pdf.set_font("Helvetica", "", 10)
            pdf.multi_cell(col_w, 6, "  " + line)

        # Numbered items
        elif re.match(r"^\d+\.", line):
            pdf.set_font("Helvetica", "", 10)
            pdf.multi_cell(col_w, 6, "  " + line)

        # Horizontal rule
        elif re.match(r"^-{3,}$", line) or re.match(r"^={3,}$", line):
            pdf.ln(2)
            pdf.set_draw_color(200, 200, 200)
            pdf.line(pdf.l_margin, pdf.get_y(), pdf.w - pdf.r_margin, pdf.get_y())
            pdf.ln(3)

        else:
            pdf.set_font("Helvetica", "", 10)
            pdf.multi_cell(col_w, 6, line)

        i += 1

    # ── Footer ──
    pdf.ln(6)
    pdf.set_font("Helvetica", "", 8)
    pdf.set_text_color(160, 152, 144)
    pdf.cell(col_w, 6, "Wayfairy - AI Travel Planner - Made with love by Hassaan Raza", align="C")

    return bytes(pdf.output())